version: "3.7"

services:
  api:
    container_name: subwayapi
    volumes:
      - node_modules:/usr/src/node_modules
      - ./api/src:/usr/src/
    build:
      context: ./api/src
      dockerfile: ../dev.dockerfile
    entrypoint: ["npm", "run", "start:dev"]
    env_file:
      - .env
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - postgres
    networks:
      - app-network
  postgres:
    container_name: postgres
    image: postgres:latest
    networks:
      - app-network
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: root
      POSTGRES_DB: db_subway
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
networks:
  app-network:
volumes:
  node_modules:






