CREATE TABLE IF NOT EXISTS train_lines (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL,
  fare NUMERIC(5, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS stations (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS train_line_stations (
  id SERIAL PRIMARY KEY,
  train_line_id INTEGER REFERENCES train_lines (id) ON DELETE CASCADE,
  station_id INTEGER REFERENCES stations (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS cards (
  id SERIAL PRIMARY KEY,
  number VARCHAR(255) UNIQUE NOT NULL,
  balance NUMERIC(10, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS rides (
  id SERIAL PRIMARY KEY,
  card_id INTEGER REFERENCES cards (id) ON DELETE CASCADE,
  station_id INTEGER REFERENCES stations (id) ON DELETE CASCADE,
  entry_exit VARCHAR(255) NOT NULL,
  timestamp TIMESTAMP NOT NULL
);